<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition="'$(Configuration)' == ''">Release</Configuration>
    <Platform Condition="'$(Platform)' == ''">x64</Platform>
    <OutputType>WinExe</OutputType>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <AssemblyName>Orla</AssemblyName>
    <RootNamespace>Orla</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <Optimize>true</Optimize>
    <ApplicationManifest>src\Orla.manifest</ApplicationManifest>
    <ApplicationIcon>Orla.ico</ApplicationIcon>
    <AppConfig>Orla.exe.config</AppConfig>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" /><Reference Include="System.Core" />
    <Reference Include="System.Web.Extensions" /><Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" /><Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Xaml" /><Reference Include="WindowsBase" />
    <Reference Include="PresentationCore" /><Reference Include="PresentationFramework" />
    <Compile Include="src\*.cs" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
